# Generated by Django 2.2.16 on 2022-02-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.CharField(help_text='Введите артикль товара', max_length=20, verbose_name='Артикль'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='caption',
            field=models.CharField(help_text='Введите название товара', max_length=30, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Выберите группу', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
    ]
